version: '3'
services:
  mydb:
    image: mysql:5.7.27
    container_name: mydb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
